require("packages/theme")
require("packages/lsp")
require("packages/treesitter")
require("packages/nvim-tree")
require("packages/telescope")
require("packages/bufferline")
require("packages/snippets")
require("packages/comment")
